"""Make team id uuid

Revision ID: 161a5b9b18ff
Revises: b31b9c699b82
Create Date: 2025-04-28 15:01:12.423965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '161a5b9b18ff'
down_revision: Union[str, None] = 'b31b9c699b82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE datasource_access ALTER COLUMN team_id TYPE UUID USING team_id::uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('datasource_access', 'team_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###