"""Add on delete cascade on team memberships

Revision ID: 2205f7657ef7
Revises: 161a5b9b18ff
Create Date: 2025-04-28 15:43:46.605223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2205f7657ef7'
down_revision: Union[str, None] = '161a5b9b18ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('team_memberships_team_id_fkey', 'team_memberships', type_='foreignkey')
    op.create_foreign_key(None, 'team_memberships', 'teams', ['team_id'], ['team_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team_memberships', type_='foreignkey')
    op.create_foreign_key('team_memberships_team_id_fkey', 'team_memberships', 'teams', ['team_id'], ['team_id'])
    # ### end Alembic commands ###
