"""Add indexes for faster retrieval

Revision ID: 348b71997440
Revises: ce9984a8da6c
Create Date: 2025-05-07 22:07:44.399785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '348b71997440'
down_revision: Union[str, None] = 'ce9984a8da6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_team_memberships_team_id'), 'team_memberships', ['team_id'], unique=False)
    op.create_index('ix_team_memberships_team_id_removed_at', 'team_memberships', ['team_id', 'removed_at'], unique=False)
    op.create_index(op.f('ix_team_memberships_user_id'), 'team_memberships', ['user_id'], unique=False)
    op.create_index('ix_team_memberships_user_id_removed_at', 'team_memberships', ['user_id', 'removed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_team_memberships_user_id_removed_at', table_name='team_memberships')
    op.drop_index(op.f('ix_team_memberships_user_id'), table_name='team_memberships')
    op.drop_index('ix_team_memberships_team_id_removed_at', table_name='team_memberships')
    op.drop_index(op.f('ix_team_memberships_team_id'), table_name='team_memberships')
    # ### end Alembic commands ###
