"""add index to team id in datasource access

Revision ID: 537fe42cab74
Revises: 33da47a14941
Create Date: 2025-05-05 14:42:54.791156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '537fe42cab74'
down_revision: Union[str, None] = '33da47a14941'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_datasource_access_team_id'), 'datasource_access', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_datasource_access_team_id'), table_name='datasource_access')
    # ### end Alembic commands ###
