"""Remove membership slug (unnecessary)

Revision ID: 79f1bf71d6c2
Revises: 8eab41baa873
Create Date: 2025-05-05 19:46:03.792913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79f1bf71d6c2'
down_revision: Union[str, None] = '8eab41baa873'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('team_memberships_membership_slug_key', 'team_memberships', type_='unique')
    op.drop_column('team_memberships', 'membership_slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_memberships', sa.Column('membership_slug', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('team_memberships_membership_slug_key', 'team_memberships', ['membership_slug'])
    # ### end Alembic commands ###
