"""Change datasource id to integer

Revision ID: 980581f22022
Revises: acd7ebce9fc1
Create Date: 2025-04-24 16:35:51.960243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '980581f22022'
down_revision: Union[str, None] = 'acd7ebce9fc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE datasource_access ALTER COLUMN datasource_id TYPE BIGINT USING (datasource_id::text::bigint)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE datasource_access ALTER COLUMN datasource_id TYPE UUID USING gen_random_uuid()')
    # ### end Alembic commands ###