"""Index datasource id in access

Revision ID: b31b9c699b82
Revises: 980581f22022
Create Date: 2025-04-28 14:56:48.474370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b31b9c699b82'
down_revision: Union[str, None] = '980581f22022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_datasource_access_datasource_id'), 'datasource_access', ['datasource_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_datasource_access_datasource_id'), table_name='datasource_access')
    # ### end Alembic commands ###
