"""Remove unique constraint

Revision ID: ce9984a8da6c
Revises: 79f1bf71d6c2
Create Date: 2025-05-06 16:17:50.715409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce9984a8da6c'
down_revision: Union[str, None] = '79f1bf71d6c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_team_user', 'team_memberships', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_team_user', 'team_memberships', ['team_id', 'user_id'])
    # ### end Alembic commands ###
